### ISSUE TITLE
Update LBS colors to match the new theme

### ISSUE THREAD

**Issue by KarlNilsson** [Lundalogik/LimeBootstrap#116]
I noticed while trying out the (currently in-development) new theme, and found that the color palette didn't update when you switch to the theme, like it does when you switch between for instance Blue and Silver. I will investigate which color palette we should use to match the rest of the client.

`SetSkin()` in src\lib\lbs.js looks to be a strong candidate

**Comment by FlippAre** [comment]
Issues fixed!
