### ISSUE TITLE
VBA classes missing in release package zip

### ISSUE THREAD

**Issue by JSandlake** [Lundalogik/LimeBootstrap#129]
lbs-2.2.0.prod

**Comment by LarsCJensen** [comment]
@FlippAre It would probably be a good idea to include everything in each release since others have missed the VBA files as well.

**Comment by FlippAre** [comment]
@LarsCJensen Yes, I do agree. Releasing is currently a manual and error prone process. I'm looking into having a CI doing it for us instead

**Comment by FlippAre** [comment]
Automatic deploy should now take care of this
