### ISSUE TITLE
Buttons should have the text (and icon) aligned to the left

### ISSUE THREAD

**Issue by justFredster** [Lundalogik/LimeBootstrap#34]
Centered alignment of the button text looks OK as long as you have one button. If you have multiple buttons it looks somewhat disorganized.

**Comment by FlippAre** [comment]
Will fix in button component

**Comment by Kahrstrom** [comment]
This has been implemented in the lbs-button component. The text can be centered with a parameter to the component, but default is left aligned. Legacy implementation has not been touched. #91
