### ISSUE TITLE
Styling on h1 and plain text needed

### ISSUE THREAD

**Issue by justFredster** [Lundalogik/LimeBootstrap#37]
Objective: Being able to add a headline and some text below it and have the headline look like an ordinary headline of a ul-list (or maybe not?) and the text nicely indented and styled. Right now, the best way to add plain instructional text in an Actionpad (with a headline) is to use:

``` html
<div class="alert">
    <ul class="menu">
        <li class="menu-header" data-bind="text:localize..."></li>
        <li class="divider"></li>
    </ul>
    <p>My very, very important, can't-live-without kind of text!
    </p>
</div>
```

It will however create quite a large gap at the top of the div.

**Comment by FlippAre** [comment]
Will be replaced by new component
