### ISSUE TITLE
Inspector reference needed for VBA datasources

### ISSUE THREAD

**Issue by justFredster** [Lundalogik/LimeBootstrap#50]
When loading a datasource you need to be able to send in the GUID for the inspector so that VBA doesn't need to use ActiveInspector as this can result in timing issues.

Discussed this with MHE.

For example something like this:
{type: 'record', source: 'ActionPad_SOS.getPersonRecord', sendinspectorid: true , alias: 'personRecord'}

**Comment by FlippAre** [comment]
We are moving away from the Use of ActiveInspector DataSources.

**Comment by justFredster** [comment]
This was fixed a long time ago but the issue was never closed it seems. The property is called "PassInspectorParam" I think.
