### ISSUE TITLE
RelatedRecord datasource fails when relation field is null

### ISSUE THREAD

**Issue by justFredster** [Lundalogik/LimeBootstrap#54]
If the relation field that a datasource of type RelatedRecord tries to load is null, loading will fail and the AP will end up in debug mode. I tested to add code in lbs.loader.js in function loadDataSource that would send in idrecord as 0 to the VBA function used if it was null. But then all bindings failed as a result of the VBA code returning Nothing. So I figure that fixing this requires more thought. What should happen? How can it be achieved? I guess the best thing is if the values used in bindings would be empty strings. But is that the case for all types of values?

**Comment by Kahrstrom** [comment]
If no one has experienced this, I'll close this issue for now. Reopen if you have new information!
