### ISSUE TITLE
Images missing in AppStore

### ISSUE THREAD

**Issue by Virulf** [Lundalogik/LimeBootstrap#61]
Hi,
Images are missing in AppStore

**Comment by ThinkFlipp** [comment]
We are working on it! Good report!

**Comment by ThinkFlipp** [comment]
Was a hard one, but should now be fixed

**Comment by Virulf** [comment]
Ser så mycket bättre ut.

Med vänliga hälsningar

Ulf Jonsson
Key Account Manager
