### ISSUE TITLE
Expose sessionId for REST requests

### ISSUE THREAD

**Issue by LLCJA** [Lundalogik/LimeBootstrap#75]
When doing REST-api requests, authentication is done with the __sessionId__ header.

In VBA the session id can be retrieved with __ActiveUser.Database.SessionID__

For every project I've involving an ActionPad and REST-api request, I've been forced to create this extra helper function in VBA to get the sessionId:
```
Public Function GetSessionId() As Variant
    On Error GoTo ErrorHandler
    GetSessionId = ActiveUser.Database.SessionID
    Exit Function
ErrorHandler:
    GetSessionId = False
    Call UI.ShowError("ActionPad.GetSessionId")
End Function
```

**Comment by FlippAre** [comment]
will be solved by #85
