### ISSUE TITLE
Expose FullActiveServerName for REST requests

### ISSUE THREAD

**Issue by LLCJA** [Lundalogik/LimeBootstrap#77]
**Application.Database.FullActiveServerName** from VBA should be exposed with lbs like **lbs.fullActiveServerName** 

To build the URL to the REST API yourself, doing like I did, is **not** recommended since we don't get the **https port** this way. In case it's not the standard 443, we have a problem.
```
'https://' + lbs.activeServer + '/' + lbs.activeDatabase + '/lime-crm-gdpr/'
```

**Comment by FlippAre** [comment]
Solved by coming #85
